version: '3.0'
services:
  web:
    image: vonzimp/magento_pwa:2.3
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
      - ../bargreen_2_3.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db     
volumes:
  db-data: 
