#!/usr/bin/env bash

su www-data <<EOSU

cd /var/www/html && composer config repositories.module-catalog-sample-data-venia git https://github.com/PMET-public/module-catalog-sample-data-venia.git
cd /var/www/html && composer config repositories.module-configurable-sample-data-venia git https://github.com/PMET-public/module-configurable-sample-data-venia.git
cd /var/www/html && composer config repositories.module-customer-sample-data-venia git https://github.com/PMET-public/module-customer-sample-data-venia.git
cd /var/www/html && composer config repositories.module-tax-sample-data-venia git https://github.com/PMET-public/module-tax-sample-data-venia.git
cd /var/www/html && composer config repositories.module-sales-sample-data-venia git https://github.com/PMET-public/module-sales-sample-data-venia.git
cd /var/www/html && composer config repositories.sample-data-media-venia git https://github.com/PMET-public/sample-data-media-venia.git

cd /var/www/html && composer update

cd /var/www/html && composer require "magento/module-catalog-sample-data-venia: dev-master"
cd /var/www/html && composer require "magento/module-configurable-sample-data-venia: dev-master"
cd /var/www/html && composer require "magento/module-customer-sample-data-venia: dev-master"
cd /var/www/html && composer require "magento/module-tax-sample-data-venia: dev-master"
cd /var/www/html && composer require "magento/module-sales-sample-data-venia: dev-master"
cd /var/www/html && composer require "magento/sample-data-media-venia: dev-master"


cd /var/www/html && bin/magento setup:upgrade && bin/magento indexer:reindex && bin/magento cache:flush && bin/magento cache:clean && bin/magento deploy:mode:set developer

EOSU

