#!/usr/bin/env bash

chown www-data:www-data /var/www/html/composer.json

su www-data <<EOSU

/var/www/html/bin/magento setup:install --base-url=$MAGENTO_URL --backend-frontname=$MAGENTO_BACKEND_FRONTNAME --language=$MAGENTO_LANGUAGE --timezone=$MAGENTO_TIMEZONE --currency=$MAGENTO_DEFAULT_CURRENCY --db-host=$MYSQL_HOST --db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER --db-password=$MYSQL_PASSWORD --use-secure=$MAGENTO_USE_SECURE --base-url-secure=$MAGENTO_BASE_URL_SECURE --use-secure-admin=$MAGENTO_USE_SECURE_ADMIN --admin-firstname=$MAGENTO_ADMIN_FIRSTNAME --admin-lastname=$MAGENTO_ADMIN_LASTNAME --admin-email=$MAGENTO_ADMIN_EMAIL --admin-user=$MAGENTO_ADMIN_USERNAME --admin-password=$MAGENTO_ADMIN_PASSWORD

cd /var/www/html && composer require --dev magento/theme-frontend-venia

cd /var/www/html && bin/magento module:enable Magento_Pwa && bin/magento setup:upgrade

/var/www/html/bin/magento setup:store-config:set --use-secure 1
/var/www/html/bin/magento setup:store-config:set --base-url-secure=https://local.magento

EOSU
